apiVersion: v2
name: parseable
description: Helm chart for Parseable Server
type: application
version: 1.5.2
appVersion: "v1.5.2"
maintainers:
  - name: Parseable Team
    email: hi@parseable.com
    url: https://parseable.com

dependencies:
- name: vector
  version: 0.20.1
  repository: https://helm.vector.dev
  condition: vector.enabled
- name: fluent-bit
  version: 0.25.0
  repository: https://fluent.github.io/helm-charts
  condition: fluent-bit.enabled
