apiVersion: v2
name: parseable
description: Parseable Helm chart - Predictive, unified observability â€” faster resolution, fewer escalations, happier customers.
type: application
version: 2.5.5
appVersion: "v2.5.5"
icon: "https://raw.githubusercontent.com/parseablehq/.github/main/images/new-logo.svg"

maintainers:
  - name: Parseable Team
    email: hi@parseable.com
    url: https://parseable.com

dependencies:
- name: vector
  version: 0.20.1
  repository: https://helm.vector.dev
  condition: vector.enabled
- name: fluent-bit
  version: 0.48.0
  repository: https://fluent.github.io/helm-charts
  condition: fluent-bit.enabled
  